from enum import Enum


class Property(Enum):
    BREEZE = 0
    STENCH = 1
    GOLD = 2
    PIT = 3
    WUMPUS = 4
    PLAYER = 5


BLACK = (0, 0, 0)
WHITE = (200, 200, 200)
BLOCK_SIZE = 128
X_TILE_COUNT = 4
Y_TILE_COUNT = 4
WINDOW_HEIGHT = BLOCK_SIZE * X_TILE_COUNT
WINDOW_WIDTH = BLOCK_SIZE * Y_TILE_COUNT
OFFSET = BLOCK_SIZE // 3
IMAGES_WIDTH = BLOCK_SIZE // 3
IMAGES_HEIGHT = BLOCK_SIZE // 3

DOWN, RIGHT, LEFT, UP = (0, 1), (1, 0), (-1, 0), (0, -1)
ACTIONS = {DOWN: "down", RIGHT: "right", LEFT: "left", UP: "up"}
